package com.kit.verifier.zeroknowledge.dto;

import java.io.Serializable;
import java.math.BigInteger;

import static com.kit.verifier.zeroknowledge.util.BigIntUtil.shortBigInt;

public class SecretOrderGroup implements Serializable {

    /**
     * Large composite that defines a group Z*_N.
     */
    private BigInteger N;

    /**
     * A generator for G, a cyclic subgroup of Z*_N with a large order. The order of this subgroup is secret.
     */
    private BigInteger g;

    /**
     * Element of group generated by g.
     * This is a generator for a subgroup of G with large order, as needed for KDLCGSO.
     */
    private BigInteger h;

    public SecretOrderGroup(BigInteger N, BigInteger g, BigInteger h) {
        this.N = N;
        this.g = g;
        this.h = h;
    }

    public BigInteger getN() {
        return N;
    }

    public BigInteger getG() {
        return g;
    }

    public BigInteger getH() {
        return h;
    }

    @Override
    public String toString() {
        return String.format("SecretOrderGroup(N=%s, g=%s, h=%s",
                shortBigInt(getN()), shortBigInt(getG()), shortBigInt(getH()));
    }
}
